version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-server:
    build: ./eureka-server
    container_name: eureka-service
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
  config-service:
    build: ./config-server
    container_name: config-service
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
#  product-service:
#    build: microservices/product-service
#    mem_limit: 512m
#    ports:
#      - "8080:8080"
#    depends_on:
#      mongodb:
#        condition: service_healthy#  product-service:
#    build: microservices/product-service
#    mem_limit: 512m
#    ports:
#      - "8080:8080"
#    depends_on:
#      mongodb:
#        condition: service_healthy
#  user-service:
#    build: microservices/user-service
#    mem_limit: 512m
#    ports:
#      - "8080:8080"
#  mongodb:
#    image: mongo:4.4.2
#    mem_limit: 512m
#    ports:
#      - "27017:27017"
#    command: mongod
#      healthcheck:
#        test: "mongo --eval 'db.stats().ok'"
#        interval: 5s
#        timeout: 2s
#        retries: 60