version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka-server:
    build: ./eureka-server
    container_name: eureka-service
    depends_on:
      - zipkin
    ports:
      - "8761:8761"
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
  config-service:
    build: ./config-server
    container_name: config-service
    depends_on:
      - eureka-server
    ports:
      - "8888:8888"
  #  movie-service:
  #    build: ./movie-service
  #    mem_limit: 512m
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - eureka-server
  #      - db_avaliacao2_movie
  #  serie-service:
  #    build: ./serie-service
  #    mem_limit: 512m
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - eureka-server
  #      - db-avaliacao2-serie
  #  catalog-service:
  #    build: ./catalog-service
  #    mem_limit: 512m
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - eureka-server
  #      - db-avaliacao2-catalog
#  db_avaliacao2_movie:
#    image: mysql:8.0
#    container_name: "db_avaliacao2_movie"
#    ports:
#      - "3306:3306"
#    volumes:
#      - db:/var/lib/mysql
#  db-avaliacao2-serie:
#    image: mongo:4.4.2
#    container_name: "db-avaliacao2-serie"
#    mem_limit: 512m
#    ports:
#      - "27017:27017"
#    command: mongod
#      healthcheck:
#        test: "mongo --eval 'db.stats().ok'"
#        interval: 5s
#        timeout: 2s
#        retries: 60
#  db-avaliacao2-catalog:
#    image: mongo:4.4.2
#    container_name: "db-avaliacao2-catalog"
#    mem_limit: 512m
#    ports:
#      - "27017:27017"
#    command: mongod
#      healthcheck:
#        test: "mongo --eval 'db.stats().ok'"
#        interval: 5s
#        timeout: 2s
#        retries: 60
