server:
  port: ${PORT:8080}

rabbitmq:
  username: ${RABBIT_USERNAME:guest}
  password: ${RABBIT_PASSWORD:guest}
  host: localhost
  port: 15672

spring:
  data:
    mongodb:
      user: test
      password: ${SENHA_DB:7890123}
      database: avaliacao2_catalog
      uri: mongodb://locallhost:27017/avaliacao2_catalog
#      uri: mongodb://db-avaliacao2-catalog:27017/avaliacao2_catalog