server:
  port: ${PORT:8080}

rabbitmq:
  username: ${RABBIT_USERNAME:guest}
  password: ${RABBIT_PASSWORD:guest}
  host: localhost
  port: 15672

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/db_avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC
#    url: jdbc:mysql://db_avaliacao2_movie:3306/avaliacao2_movie
    password: ${SENHA_DB:7890123}
  jpa:
    dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  #apenas para gerar o create.sql na root para popular-mos o schema no postgres
#  properties:
#    javax:
#      persistence:
#        schema-generation:
#          create-source: metadata
#          scripts.action: create
#          scripts.create-target: create.sql
#    hibernate.hbm2ddl.delimiter: ';'
#
#queue:
#  movie:
#    name: MovieQueue