spring:
  application:
    name: movie-service
  config:
    import: optional:configserver:http://config-service:8888
  #    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${PROFILE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SENHA_DB:7890123}
    url: jdbc:mysql://db_avaliacao2_movie:3307/avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC
   #url: jdbc:mysql://localhost:3306/avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: localhost
    port: 5672
  #apenas para gerar o create.sql na root para popular-mos o schema no postgres
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#        hibernate.hbm2ddl.delimiter: ';'

eureka:
  instance:
    #    hostname: localhost
    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

queue:
  api-movie:
    name: movieQueue

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de gerenciamento das operacoes no cinema.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio


