spring:
  application:
    name: movie-service
  config:
#    import: optional:configserver:http://config-service:8888
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${PROFILE:dev}

eureka:
  instance:
    hostname: localhost
#    hostname: eureka-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

queue:
  api-movie:
    name: movieQueue

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de gerenciamento das operacoes no cinema.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio

