spring:
  application:
    name: serie-service
  config:
    import: optional:configserver:http://config-service:8888
#    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${PROFILE:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${SENHA_DB:7890123}
    url: jdbc:mysql://db_avaliacao2_movie:33060/avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC
    #    url: jdbc:mysql://localhost:33061/avaliacao2_movie?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimeZone=UTC
    jpa:
      properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
eureka:
  instance:
    hostname: eureka-service
#    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

queue:
  api-serie:
    name: serieQueue

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de gerenciamento das operacoes de Series.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio

